---
title: "reproducible-dataviz"
author: "Julien Brun"
date: "9/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reproducible Analysis with Rmarkdown

### Dive in: Create our first RMarkdown

### Show the gallery

https://rmarkdown.rstudio.com/gallery.html

Demo time

### Intro Slides

- Why reproducible science
- How Rmarkdown (and friends) can help
  - Combine code and documentation in **one** document/file: literate programming
  - Help to compile compelling documents (reports, journal articles, presentations, ...)
  - Easy to share through various formats (websites, blogs, dashboards, interactive visualizations)
  - Can even let you run other scripting languages (Python, SQL, ...)


- What is Rmarkdown
  - Markdown is a simple (read easy to use) text-based markup for creating easy to read documents to be converted to HTML, PDF, docx and other formats. Document styles can be customised with HTML/CSS and math notation can be included using LaTeX or mathjax. (From: [RopenSci reproducibility guide](http://ropensci.github.io/reproducibility-guide/sections/tools/))
 
  
  - the **R** flavor
    - R Markdown: An enhanced flavor of Markdown that recognizes R code chunks, which allows the embedding of R directly into a Markdown document to create dynamic and reproducible documents. (From: [RopenSci reproducibility guide](http://ropensci.github.io/reproducibility-guide/sections/tools/))


  
- What can you do with Rmarkdown
  - Document extensively your analysis
  - Share results (figures and tables)
  - Let others execute and modify your code
  - Create interactive documents
  - Create websites and blog
  - Write journal articles and Books
- What Rmarkdown can not help you with
  - Data management and access
  - Capture your computing environment
  - Modularize your code

### Hands on exercise

- Use data from LTER
  Potentially: https://nceas.github.io/metajam/articles/dataset-batch-processing.html
- show a compelling data analysis with it
- open the floor to cool data visualizations for the ggplot2 part of the training


## References

- RStudio Material on Rmarkdown : https://rmarkdown.rstudio.com/articles.html
- RStudio Gallery: https://rmarkdown.rstudio.com/gallery.html
- Rmarkdown cheat sheet: https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf
- Reference guide : https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf
- GitHub Intro to Markdown: https://guides.github.com/features/mastering-markdown/

